#开发环境配置

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resource_sharing_platform?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111222
server:
  port: 8080